import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import pretendard from "@/app/fonts/pretendard"; // 추가

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={`${pretendard.variable} `}>
      <body className="">
        <Navbar />
        <div className="px-16 py-10 justify-center">{children}</div>
      </body>
    </html>
  );
}
